config/routes.rb
Rails.application.routes.draw do
  root to: 'party#index'

  match 'signout', to: 'application#destroy', as: 'signout', via: [:get, :post]

  get 'receive_sms' => "notification#receive_sms", :as => :receive_sms
  post 'receive_sms' => "notification#receive_sms"

  get 'retrieve_video_id' => "party#retrieve_video_id"
  post 'retrieve_video_id' => "party#retrieve_video_id"

  get 'about_us' => "party#about_us"
  get 'instructions' => "party#instructions"
  get 'team' => "party#team"
  get 'retrieve_next_video_id' => "party#retrieve_next_video_id"

  get 'retrieve_comments' => "comment#retrieve_comments"

  get 'retrieve_queue' => "party#retrieve_queue"
  get 'retrieve_party' => "party#show"

  resources :party, only: [:show, :new, :create, :retrieve_video_id]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SuprStarMe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script type="text/javascript">
  function parseVideo (json) {
    console.log(json);
    song_object = json;
  }
  </script>
  <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/jquery-ui.min.js"></script>
  <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/themes/smoothness/jquery-ui.css" />
  <script type="text/javascript" src="http://www.suprstar.me/retrieve_video_id.js?callback=parseVideo"></script>
  <script type="text/javascript" src="http://suprstar.herokuapp.com/retrieve_video_id.js?callback=parseVideo"></script>
  <script src="//www.google.com/jsapi" type="text/javascript"></script>
  <script type="text/javascript">google.load("swfobject", "2.1")</script>
  <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400italic' rel='stylesheet' type='text/css'>

  <%= csrf_meta_tags %>
</head>
<body>
<nav>
  <div class="navbar-header">
    <% if current_page?(retrieve_party_path) %>
      <h1>SuprStar.me</h1>
    <% else %>
      <h1 class="links"><%= link_to "SuprStar.me", root_path %></h1>
    <% end %>
  </div>

  <div class="navbar-contact-info">
    <ul class="nav navbar-nav">
    <% if current_party %>
      <%= link_to signout_path, id: "sign_out" do %>
      <li>End Party?</li>
    <% end %>
      <% else %>
      <li class="links"><%= link_to "About", about_us_path %></li>
      <li class="links"><%= link_to "Team", team_path %></li>
      <li class="links"><%= link_to "Instructions", instructions_path %></li>
    <% end %>
  </ul>
  </div>


  <div class="navbar-li">
    <ul class="nav navbar-nav pull-right">
    </ul>
  </div>
</nav>
<%= yield %>

</body>
</html>